name: Ci and Cd

on:
  push:
    branches:
      - develop
      - main

jobs:
  develop:
    name: Test and linting
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.0

      - name: Install dependencies
        working-directory: ./project
        run: npm install

      - name: Linting
        working-directory: ./project
        run: npm run lint

  staging:
    name: Push to docker hub
    runs-on: ubuntu-22.04
    if: ${{github.ref == 'refs/heads/develop'}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login into docker hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}


      - name: Deploy history service to dockerhub
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:project"
          push: true
          build-args: |
            VITE_SERVICE_ID=${{secrets.VITE_SERVICE_ID}}
            VITE_PUBLIC_KEY=${{secrets.VITE_PUBLIC_KEY}}
            VITE_TEMPLATE_ID=${{secrets.VITE_TEMPLATE_ID}}
          tags: ${{secrets.DOCKER_USERNAME}}/portofolio:${{secrets.DOCKER_PORTOFOLIO_TAGS_APP}}