name: Ci and Cd

on:
  push:
    branches:
      - develop
      - main

jobs:
  ci:
    name: Setup nodejs
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./project

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.0

      - name: Install dependencies
        run: npm install

      - name: Linting
        run: npm run lint

      - name: Build project
        run: npm run build

  cd:
    name: CD processes
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./project

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Docker
        uses: docker/setup-buildx-action@v1

      - name: Login into docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

      - name: Build history service application, and deploy to dockerhub
        run: |
          docker build -t portofolio:${{secrets.DOCKER_TAGS_APP}} .
          docker push portofolio:${{secrets.DOCKER_TAGS_APP}} ${{secrets.DOCKER_USERNAME}}
